[ADD] Cart_ProductList 조회 API
wecode-bootcamp-korea/36-1st-DevMarket-backend pull request #9
Opened 2022-08-23 04:04 UTC by jungsae

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)
- [GET] 유저의 쇼핑카트 상품리스트 조회 엔드포인트 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
*특이사항*
 - (아직 회원가입, 토큰 인증/인가 기능을 맡은 조원과 코드를 병합 하지 않은 상태라 현재는 request의 body에서 유저의 이름이나 아이디를 받아오지만, 병합 후에는 토큰에서 이름이나 아이디를을 가져오는 방향으로 수정 할 예정입니다)

1. 유저의 쇼핑카트 상품리스트 조회
- request 요청에서 유저의 아이디를 받아서, 그 유저가 넣은 상품들을 조회합니다.
- controller단에서 유효한 입력값 들어왔는지 키에러 체크.
- 성공시 200 status code 반환.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-08-23 05:17 UTC, lordmyshepherd requested changes

2022-08-23 05:17 UTC, lordmyshepherd commented on controllers/cartController.js
> +const cartList = async(req, res) => {
장바구니 목록은 로그인한 사용자만이 접근 가능합니다.
그렇기 때문에, cartRouter.js에서 인증 middleware를 추가해주세요.

2022-08-23 05:17 UTC, lordmyshepherd commented on controllers/cartController.js
> +const cartList = async(req, res) => {
함수 이름은 동사로 만들어야 합니다.

`cartList` -> `getCarts` 혹은 `getCartLists`로 수정해주세요.

2022-08-23 05:17 UTC, lordmyshepherd commented on controllers/cartController.js
> +        const list = await cartService.cartList(userId);
Service에 있는 함수도 마찬가지로 `cartList` -> `getCarts` 혹은 `getCartLists`로 수정해주세요.

```suggestion
        const list = await cartService.getCartList(userId);
```

2022-08-23 05:17 UTC, lordmyshepherd commented on services/cartService.js
> +};
한 줄로 줄일 수 있을 것 같습니다.
일반적으로 한 줄에 문자가 80 이하인 경우에는 한 줄로 표현하는 것이 가독성이 좋습니다.
```suggestion
const getCarts = async (userId) => await cartDao.productList(userId)
```

2022-08-23 05:17 UTC, lordmyshepherd commented on models/cartDao.js
> +        throw error;
Error 객체를 만들 때에도 굉장히 많은 코드가 중복되는 것을 느끼셨을 것 같습니다.

Node.js 내장 Error 객체를 사용하는 것은 대부분의 개발자가 오류의 근원을 추적하기 위해 의존하는 StackTrace와 같은 오류에 대한 직관적이고 명확한 정보를 포함하고 있기 때문에 좋은 방법입니다. 그리고 HTTP 상태 코드와 같은 의미 있는 추가 속성과 Error 클래스를 확장하여 설명을 추가하면 더 많은 정보를 얻을 수 있습니다.

예를 들어서 아래와 같이 사용할 수 있겠습니다.
```javascript
class BaseError extends Error {
	constructor(name, httpStatusCode, description) {
		super(description);
	
		this.name = name;
		this.httpCode = httpStatusCode;
	
		Error.captureStackTrace(this);
	}
}

if (user === null) 
	throw new BaseError(
		'NOT FOUND',
		HttpStatusCode.NOT_FOUND,
		true,
		'detailed explanation'
);
```

2022-08-24 05:49 UTC, lordmyshepherd commented on models/cartDao.js
> +        throw error;
피드백 적용이 아직 안된 것 같습니다! 반영 부탁드려요!

2022-08-24 05:53 UTC, jungsae commented on models/cartDao.js
> +        throw error;
넵!

2022-08-24 06:36 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-08-24 06:36 UTC, merged